spring:
  application:
    name: ms-items-svc
  profiles:
    active: default
    
server:
  port: 8002

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
  client:
    service-url:
      defaultZone: http://eurekasrv.dsbms.lomosrv.com:8761/eureka
      
sbms:
  api:
    products:
      endpoint: http://products.dsbms.lomosrv.com
      resource: /sbms/products